import { sanitizeExternalText } from "./generateProductUpdates";
import type { ProductUpdateDraft, PullRequestDecision } from "./productUpdates";
import { readProductUpdateSpec } from "./productUpdateSpec";

export type ClassifiedCommit =
  | { kind: "pull_request"; number: number; headRef?: string; sha: string }
  | { kind: "branch_sync"; sha: string; subject: string }
  | { kind: "unresolved"; sha: string; subject: string };

export type ParsedPullRequestRef = {
  number: number;
  headRef?: string;
};

export type SourcePullRequestRecord = {
  number: number;
  title: string;
  body: string | null;
  mergedAt: string | null;
  baseRef: string;
  headRef: string;
  authorType: string;
};

const MERGE_PULL_REQUEST_PATTERN = /^Merge pull request #(\d+) from (\S+)/;
const MERGE_BRANCH_PATTERN = /^Merge branch /;

/** Drop the `owner:` (fork) prefix. Bare branch names such as `release/m16` stay intact. */
export function normalizeHeadRef(raw: string): string {
  const colonIndex = raw.indexOf(":");
  if (colonIndex >= 0) {
    return raw.slice(colonIndex + 1);
  }
  return raw;
}

/** Merge-commit subjects carry `owner/branch` (same repo) or `owner:branch` (fork); strip the owner segment only. */
export function normalizeMergeSubjectHeadRef(raw: string): string {
  if (raw.indexOf(":") >= 0) {
    return normalizeHeadRef(raw);
  }
  const slashIndex = raw.indexOf("/");
  return slashIndex >= 0 ? raw.slice(slashIndex + 1) : raw;
}

/** Integration pull requests carry whole branches (preview/release/*) into main, not user changes. */
export function isIntegrationHeadRef(headRef: string | undefined): boolean {
  if (!headRef) {
    return false;
  }
  const normalized = normalizeHeadRef(headRef);
  const candidates = [normalized];
  const slashIndex = normalized.indexOf("/");
  if (slashIndex >= 0) {
    candidates.push(normalized.slice(slashIndex + 1));
  }
  return candidates.some(
    (candidate) =>
      candidate === "preview" || candidate === "main" || candidate.startsWith("release/"),
  );
}

/**
 * Classify `git log` entries in the release range.
 *
 * - `Merge pull request #N from ...` commits map to PR N directly (the message is
 *   generated by GitHub at merge time and is authoritative).
 * - `Merge branch ...` commits are branch syncs with no PR and are skipped.
 * - Every other commit is "unresolved" and must be mapped to its merged PR via the
 *   `commits/{sha}/pulls` API. Squash-merge `(#N)` subject suffixes are deliberately
 *   not trusted: they can contain issue references instead of the PR number.
 */
export function classifyCommitSubjects(
  entries: Array<{ sha: string; subject: string }>,
): ClassifiedCommit[] {
  return entries.map(({ sha, subject }) => {
    const line = subject.trim();
    const mergeMatch = MERGE_PULL_REQUEST_PATTERN.exec(line);
    if (mergeMatch) {
      const number = Number(mergeMatch[1]);
      if (Number.isSafeInteger(number) && number > 0) {
        return {
          kind: "pull_request",
          number,
          headRef: normalizeMergeSubjectHeadRef(mergeMatch[2]),
          sha,
        };
      }
    }
    if (MERGE_BRANCH_PATTERN.test(line)) {
      return { kind: "branch_sync", sha, subject: line };
    }
    return { kind: "unresolved", sha, subject: line };
  });
}

export type ReleaseBoundary =
  | { kind: "resolved"; boundarySha: string; note?: string }
  | { kind: "initial_release" }
  | { kind: "error"; reason: string };

/**
 * Resolve the commit-range boundary for this release: the previous release's recorded
 * sourceSha, or (for legacy assets) the previous release tag's commit. Falls back to
 * the merge-base when the recorded boundary is not an ancestor of the source commit.
 */
export function resolveReleaseBoundary(options: {
  previousSourceSha?: string;
  latestReleaseTag?: string;
  sourceSha: string;
  revParse: (ref: string) => string | undefined;
  mergeBase: (a: string, b: string) => string | undefined;
}): ReleaseBoundary {
  const { previousSourceSha, latestReleaseTag, sourceSha, revParse, mergeBase } = options;

  let boundarySha = previousSourceSha;
  let boundaryNote: string | undefined;
  if (!boundarySha && latestReleaseTag) {
    boundarySha = revParse(`refs/tags/${latestReleaseTag}^{commit}`);
    if (!boundarySha) {
      return {
        kind: "error",
        reason: `前回リリース ${latestReleaseTag} のコミットを解決できません`,
      };
    }
    boundaryNote = `前回リリース ${latestReleaseTag} を境界に使用`;
  }
  if (!boundarySha) {
    return { kind: "initial_release" };
  }
  if (boundarySha === sourceSha) {
    return {
      kind: "resolved",
      boundarySha,
      note: "前回リリースと同一コミットのため収集対象なし",
    };
  }

  const base = mergeBase(boundarySha, sourceSha);
  if (!base) {
    return {
      kind: "error",
      reason: `前回境界 ${boundarySha} と対象 ${sourceSha} に共通祖先がありません`,
    };
  }
  if (base !== boundarySha) {
    return {
      kind: "resolved",
      boundarySha: base,
      note: `前回境界 ${boundarySha} が対象コミットの祖先でないため merge-base ${base} を使用`,
    };
  }
  return { kind: "resolved", boundarySha, note: boundaryNote };
}

/** Build a user-facing update title from a pull request title. */
const CONVENTIONAL_TITLE_PREFIX =
  /^(?:feat|fix|docs|chore|refactor|perf|style|test|build|ci|revert)(?:\([^)]*\))?!?\s*:\s*/i;
const TRAILING_PR_REFERENCE = /\s*\(#\d+\)\s*$/;

export function titleForProductUpdate(title: string): string {
  const sanitized = sanitizeExternalText(title);
  const cleaned = sanitized
    .replace(CONVENTIONAL_TITLE_PREFIX, "")
    .replace(TRAILING_PR_REFERENCE, "")
    .trim();
  return cleaned === "" ? sanitized : cleaned;
}

export type PullRequestCollection = {
  decisions: PullRequestDecision[];
  drafts: ProductUpdateDraft[];
  errors: string[];
};

/**
 * Apply the suzumemo-update spec to every in-range pull request and produce drafts plus
 * the per-PR decision record. Extraction failures stay errors: they are never converted
 * into an implicit "no changes" outcome.
 */
export function collectPullRequestDecisions(
  refs: ParsedPullRequestRef[],
  pullRequests: SourcePullRequestRecord[],
  unpublishedNumbers?: Set<number>,
): PullRequestCollection {
  const records = new Map(pullRequests.map((record) => [record.number, record]));
  const decisions: PullRequestDecision[] = [];
  const drafts: ProductUpdateDraft[] = [];
  const errors: string[] = [];

  for (const ref of refs) {
    const record = records.get(ref.number);
    const headRef = record?.headRef ?? ref.headRef;

    if (isIntegrationHeadRef(headRef)) {
      decisions.push({
        pullRequest: ref.number,
        outcome: "integration",
        reason: `統合PR(head: ${headRef})のため収集対象外`,
      });
      continue;
    }

    if (!record) {
      errors.push(`PR #${ref.number}: GitHub API から取得できませんでした`);
      continue;
    }

    if (record.mergedAt === null) {
      decisions.push({
        pullRequest: ref.number,
        outcome: "not_merged",
        reason: "マージされていないPR参照のため対象外",
      });
      continue;
    }

    if (unpublishedNumbers && !unpublishedNumbers.has(ref.number)) {
      decisions.push({
        pullRequest: ref.number,
        outcome: "skipped",
        reason: "既に公開済みの更新履歴に含まれるため対象外",
      });
      continue;
    }

    if (record.authorType === "Bot") {
      decisions.push({
        pullRequest: ref.number,
        outcome: "exempt_bot",
        reason: "bot作成PRのため記入対象外",
      });
      continue;
    }

    const specResult = readProductUpdateSpec(record.body);
    if (!specResult.ok) {
      errors.push(`PR #${ref.number}: ${specResult.errors.join(" / ")}`);
      continue;
    }

    const spec = specResult.spec;
    if (spec.publish === false) {
      decisions.push({
        pullRequest: ref.number,
        outcome: "skipped",
        reason: spec.reason,
      });
      continue;
    }

    const title = titleForProductUpdate(record.title);
    const summary = sanitizeExternalText(spec.description);
    if (title === "" || summary === "") {
      errors.push(
        `PR #${ref.number}: 掲載原稿から title/summary を組み立てられませんでした(title="${record.title}")`,
      );
      continue;
    }

    const updateId = `pr-${ref.number}`;
    drafts.push({ id: updateId, title, summary, category: spec.category });
    decisions.push({
      pullRequest: ref.number,
      outcome: "published",
      reason: `category: ${spec.category}`,
      updateId,
    });
  }

  return { decisions, drafts, errors };
}
