import type { WeeklyExpenseChartData } from "../utils/weeklyExpenseChartData";
import type { CategorySummary, IncomeItem, ReceiptItem } from "../../summary-shared/types/types";

export type WeeklySummaryPanelProps = {
  count: number;
  totalAmountYen: number;
  totalIncomeYen?: number;
  incomeCount?: number;
  byCategory: CategorySummary[];
  prevWeekTotalAmountYen: number | null;
  receipts: ReceiptItem[];
  incomes?: IncomeItem[];
  isLoading?: boolean;
  weekStartDate: string;
  weeklyExpenseTrend?: WeeklyExpenseChartData | null;
  onDeleteReceipt?: (receipt: ReceiptItem) => void;
  onEditReceipt?: (receipt: ReceiptItem) => void;
  selectionEnabled?: boolean;
  selectedCount?: number;
  limitMessage?: string;
  previewCategory?: { _id: string; name: string; color?: string } | null;
  saving?: boolean;
  isSelected?: (receipt: ReceiptItem) => boolean;
  onToggleSelection?: (receipt: ReceiptItem, checked: boolean) => void;
  onSelectVisible?: (receipts: ReceiptItem[]) => void;
  onDeselectVisible?: (receipts: ReceiptItem[]) => void;
  onClearSelection?: () => void;
  onBulkChangeCategory?: () => void;
  onBulkDelete?: () => void;
};
